name: workflow analysis
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: workflow information
        run: echo "${{github}}"
  output-with-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: workflow information
        run: |
          echo "${{toJSON(github)}}"
          echo  "my name is lakhan"
