name: node
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      
      - name: read directory
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
          with:
            node-version: 18
      
      - name: install dependencies packages
        run: npm install
      
      - name: test 
        run: npm test
        